### PR TITLE
Add ability to send notifications asynchronously

### LINKED ISSUE #38: Add asynchronous mode
For sites with lots of people getting notified, we need to send notifications in a separate thread. I think this makes most sense in a cron one-off task, as combined with Cavalcade, this solves all our problems.

### PR DESCRIPTION
**Pull request by rmccue**
Fixes #38.

### CODE REVIEW

**Comment by rmccue** [comment]
@joehoyle Can I get a review on this one? :P

**Comment by joehoyle** [comment]
Is doing async that important? Wondering what the slow down is with using sync.

**Comment by rmccue** [comment]
When a post is created, there's a synchronous call for every subscribed user to the mail API (Mandrill/Postmark), which also sends the email synchronously. Testing this locally confirmed a significant speed up and unblocking on publish.

**Comment by joehoyle** [comment]
:+1: :eyes:

**Pull request merged**
